### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by waissbluth** [nodetiles/nodetiles-postgis#2]
Probably an outdated `pg` dependency?

I wonder how I can get the postgis adapter to work with the nodetiles-init example.

This is what I get:

```
nwr$ npm install nodetiles-postgis
npm WARN package.json nodetiles-server-example@0.0.1 No repository field.
-
> pg@1.0.4 install /Users/nwr/Downloads/nodetiles-init-master/node_modules/nodetiles-postgis/node_modules/pg
> node-gyp rebuild || (exit 0)

  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:36:27: error: expected class name
class Connection : public ObjectWrap {
                          ^
../src/binding.cc:84:12: error: unknown type name 'uv_poll_t'
  io_event(uv_poll_t* w, int status, int revents)
           ^
../src/binding.cc:100:17: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  Connect(const Arguments& args)
                ^~~~~~~~~
                v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:120:16: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  Cancel(const Arguments& args)
               ^~~~~~~~~
               v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:136:19: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  SendQuery(const Arguments& args)
                  ^~~~~~~~~
                  v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:159:29: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  SendQueryWithParams(const Arguments& args)
                            ^~~~~~~~~
                            v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:168:21: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  SendPrepare(const Arguments& args)
                    ^~~~~~~~~
                    v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:183:27: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  SendQueryPrepared(const Arguments& args)
                          ^~~~~~~~~
                          v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:191:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  DispatchParameterizedQuery(const Arguments& args, bool isPrepared)
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:235:13: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  End(const Arguments& args)
            ^~~~~~~~~
            v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:245:3: error: unknown type name 'uv_poll_t'
  uv_poll_t read_watcher_;
  ^
../src/binding.cc:246:3: error: unknown type name 'uv_poll_t'
  uv_poll_t  write_watcher_;
  ^
../src/binding.cc:273:27: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  SendCopyFromChunk(const Arguments& args) {
                          ^~~~~~~~~
                          v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:284:21: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  EndCopyFrom(const Arguments& args) {
                    ^~~~~~~~~
                    v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:300:14: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  New (const Arguments& args)
             ^~~~~~~~~
             v8::internal::Arguments
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:44:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/binding.cc:45:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value> (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/nwr/.node-gyp/0.12.2/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../src/binding.cc:48:29: error: no member named 'NewSymbol' in 'v8::String'
    t->SetClassName(String::NewSymbol("Connection"));
                    ~~~~~~~~^
../src/binding.cc:50:19: error: use of undeclared identifier 'NODE_PSYMBOL'
    emit_symbol = NODE_PSYMBOL("emit");
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nwr/Downloads/nodetiles-init-master/node_modules/nodetiles-postgis/node_modules/pg
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
nodetiles-postgis@0.1.0 node_modules/nodetiles-postgis
├── lodash@1.2.1
└── pg@1.0.4 (generic-pool@2.0.2, buffer-writer@1.0.0)
```

**Comment by waissbluth** [comment]
Maybe the `pg`dependency should be upgraded to something higher? It's currently ~1.0. @Mr0grog?

**Comment by Mr0grog** [comment]
Oh no, sorry I didn’t see this earlier. Just realized I’m not watching this repo for some reason :\

You’re probably right on the versioning—1.0 is waaaay out of date. I’ll take a closer look as soon as I get a chance, but that probably won’t be until later today.

**Comment by Mr0grog** [comment]
Or, if you have a working update, @waissbluth, feel free to submit a PR.

**Comment by waissbluth** [comment]
Thanks! Unfortunately I have not been able to figure it out, so I have not
much to contribute

On Thu, Apr 30, 2015 at 2:20 PM, Rob Brackett notifications@github.com
wrote:

> Or, if you have a working update, @waissbluth
> https://github.com/waissbluth, feel free to submit a PR.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodetiles/nodetiles-postgis/issues/2#issuecomment-97885855
> .

## 

Nicolás Waissbluth Razmilic

**Comment by Mr0grog** [comment]
@waissbluth Try giving the `update-dependencies` branch a try and let me know if that works before I merge it.

**Comment by waissbluth** [comment]
`npm install` works on this branch. Thank you!

On Thu, Apr 30, 2015 at 7:21 PM, Rob Brackett notifications@github.com
wrote:

> @waissbluth https://github.com/waissbluth Try giving the
> update-dependencies branch a try and let me know if that works before I
> merge it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodetiles/nodetiles-postgis/issues/2#issuecomment-97988707
> .

## 

Nicolás Waissbluth Razmilic

**Comment by Mr0grog** [comment]
Great, merged the fix in, so I’ll close this.
